# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris Salzberg
email: me@chrissalzberg.com
description: >- # this means to ignore newlines until "baseurl:"
  The site of Chris Salzberg, Ruby on Rails programmer, writer and speaker based in Japan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrissalzberg.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shioyama
github_username:  shioyama
stackoverflow_username: 820254/chris-salzberg
logo: /assets/chrissalzberg-c64.png
author: shioyama
twitter:
  username: shioyama
  card: summary
  title: Chris Salzberg
social:
  name: shioyama
  links:
    - https://twitter.com/shioyama
    - https://github.com/shioyama
    - https://keybase.io/shioyama
    - https://stackoverflow.com/users/820254/chris-salzberg

# Build settings
markdown: kramdown
plugins:
  #- jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
